### ISSUE TITLE
Classify and optimize weather data presentation

### ISSUE THREAD

**Issue by JayRMagee** [sdmila/weatherlens#11]

**Comment by sdmila** [comment]
We are going with an OOP approach to our weather data elements. Simply put: a weather forecast should be a class, WeatherForecast, that holds all the necessary data in the form of class fields. A proper architecture should be defined for what classes need to be created and utilized for display on a home page.

**Comment by sdmila** [comment]
With the recent implementation of geolocation, we managed to do quite a bit of the reclassification of objects involved in this system. This issue has been resolved.
